### ISSUE TITLE
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### ISSUE THREAD

**Issue by andyyuan78** [renmengye/imageqa-public#1]
envy@ub1404:~/os_pri/github/imageqa-public/src$ GNUMPY_USE_GPU=yespython python train.py -model ../models/2_vis_blstm.model.yml -output ../results -data ../data/cocoqa -config ../config/train.yml
Initializing weights for imgFeat
Reading ../data/hidden_oxford_mscoco.h5
(123287, 4096)
Epoch size: 70854
Batch size: 100
Step size: 709
Examples per step: 70854
Steps per epoch: 1
Trainer 2_vis_blstm-v-20160323-095803
.Traceback (most recent call last):
  File "train.py", line 307, in <module>
    validInputWeights)
  File "train.py", line 156, in trainValid
    validInputWeights=validInputWeights)
  File "/home/envy/os_pri/github/imageqa-public/src/nn/trainer.py", line 264, in train
    self.model.backward(dEdY)
  File "/home/envy/os_pri/github/imageqa-public/src/nn/container.py", line 130, in backward
    self.stages[s].graphBackward()
  File "/home/envy/os_pri/github/imageqa-public/src/nn/stage.py", line 144, in graphBackward
    dEdX = self.backward(self.dEdY)
  File "/home/envy/os_pri/github/imageqa-public/src/nn/lut.py", line 96, in backward
    if X[n] != 0:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
envy@ub1404:~/os_pri/github/imageqa-public/src$

**Comment by renmengye** [comment]
Thanks for reporting the issue. It has been resolved in the most recent commit.

**Comment by andyyuan78** [comment]
it works
